### ISSUE TITLE
Are there files missing in the misc folder?

### ISSUE THREAD

**Issue by spur9** [NPLawrence/StableBehavior.jl#1]
After I configured the environment, when I used the include command to execute the plots.jl file in the misc folder, it showed that the LTIEnv file was called. The system prompted me that LTIEnv was not found. Later, I copied the LTIEnvPID in the env folder to misc and changed it. Its file name is LTIEnv, but it still doesn't work. I want to know if the LITEnv file is missing?
Please look at the statement on line 20 in the plots.jl file

**Comment by NPLawrence** [comment]
Thanks for the catch. `LTIEnv` is just a remnant and can be ignored. I've deleted references to it in the current version. (The misc folder is basically an archive of a bunch of helper functions for generating the plots in the paper.)

**Comment by spur9** [comment]
Thank you for your reply.I would like to know which part of the paper "Stabilizing reinforcement learning control: A modular framework for optimizing over all stable behavior" your open source code corresponds to, and what is the function of the code in your src folder? I see that almost all of them are functions, but I don’t quite understand the functions of these functions.

**Comment by NPLawrence** [comment]
Fair enough. The scripts to run the examples are [here](../blob/main/examples), while supporting code is under the [src](../blob/main/src) files. The src files contain things like the environments, policy structures, and misc data processing functions, while the examples run RL algorithms from [ReinforcementLearning.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl) using the custom types in the src.
